#!/usr/bin/env bash
# This script displays "Best School" 10 times and prints "Hi" after the 9th "Best School"

count=1
while [ $count -le 10 ]
do
  echo "Best School"
  if [ $count -eq 9 ]; then
    echo "Hi"
  fi
  ((count++))
done
