#!/usr/bin/env bash
# This script prints numbers from 1 to 20 with special messages on 4, 9, and 17 using a case statement in a while loop

count=1
while [ $count -le 20 ]
do
  echo "$count"
  case $count in
    4)
      echo "bad luck from China"
      ;;
    9)
      echo "bad luck from Japan"
      ;;
    17)
      echo "bad luck from Italy"
      ;;
  esac
  ((count++))
done
